[package]
name = "rips"
version = "0.0.0"
authors = ["Linus FÃ¤rnstrand <faern@faern.net>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/faern/librips"
description = "Rust TCP/IP Stack - A full userspace TCP/IP stack written in Rust"
readme = "README.md"

[dependencies]
#ipnetwork = "0.7.0"
pnet = "0.12.0"

#[dependencies.pnet]
#git = "https://github.com/faern/libpnet"
#branch = ""
#path = "../libpnet"

[dependencies.ipnetwork]
git = "https://github.com/faern/ipnetwork"
#path = "../ipnetwork"
